blueprint:
  name: Motion-based lighting with multiple time periods (RGB or scenes)
  description: >
    When motion is detected, turn on different lights/brightness/RGB or scenes
    depending on the current time period, then turn them off after a configurable
    no-motion delay for that period. One automation can cover a whole day's
    behavior.
  domain: automation
  input:
    motion_sensors:
      name: Motion sensors
      description: One or more motion sensors that will trigger this automation.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
          multiple: true

    control_mode:
      name: Control mode
      description: >
        Choose whether this blueprint uses direct light control (brightness + RGB)
        or scenes for each time period.
      default: lights
      selector:
        select:
          options:
            - lights
            - scenes

    off_lights:
      name: Lights to turn off
      description: >
        Lights that should be turned off after the no-motion delay. This should
        include any lights that might be turned on by this automation (whether
        via direct control or via scenes).
      selector:
        target:
          entity:
            domain: light

    # -------- TIME PERIOD 1 --------
    period1_start:
      name: Period 1 start time
      selector:
        time:
    period1_end:
      name: Period 1 end time
      selector:
        time:
    period1_off_delay:
      name: Period 1 off delaysed when Control mode = scenes).
      selector:              od 4 end time
      selector:
        time:
    period4_off_delay:       -------- PERIOD 2 ----------
      - conditions:
          - condition: template
            value_template: ta:
                      brightness_pct: !input period2_brightness
                      rgb_c     value_template: >
              {% set now_time = now().strftime('%H:%M:%S') %}
              {% set start = period3_start %}
              {% set end =  rgb_color: !input period3_color
              - conditions:
                  - condition: template
                    value_template: "{{ control_mode == 'scenes' }}"
                sequence:
                  - serv           {% set start = period4_start %}
              {% set end = period4_end %}
              {% if staion: template
                    value_template: "{{ control_mode == 'scenes' }}"
                sequence:
                  - service: scene.turn_on
                    target:
                      entity_id: !input period4_scene

          - wait_for_trigger:
              - platform: state
                entity_id: !input motion_sensors
                to: 'off'
                for: !input period4_off_delay

          - service: light.turn_off
            target: !input off_lightsrt <= end %}
                {{ start <= now_time < end }}
              {% else %}
                {{ now_time >= start or now_time < end }}
              {% endif %}
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ control_mode == 'lights' }}"
                sequence:
                  - service: light.turn_on
                    target: !input period4_lights
                    data:
                      brightness_pct: !input period4_brightness
                      rgb_color: !input period4_color
              - conditions:
                  - conditice: scene.turn_on
                    target:
                      entity_id: !input period3_scene

          - wait_for_trigger:
              - platform: state
                entity_id: !input motion_sensors
                to: 'off'
                for: !input period3_off_delay

          - service: light.turn_off
            target: !input off_lights

      # ---------- PERIOD 4 ----------
      - conditions:
          - condition: template
            value_template: >
              {% set now_time = now().strftime('%H:%M:%S') %}
    period3_end %}
              {% if start <= end %}
                {{ start <= now_time < end }}
              {% else %}
                {{ now_time >= start or now_time < end }}
              {% endif %}
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ control_mode == 'lights' }}"
                sequence:
                  - service: light.turn_on
                    target: !input period3_lights
                    data:
                      brightness_pct: !input period3_brightness
                    olor: !input period2_color
              - conditions:
                  - condition: template
                    value_template: "{{ control_mode == 'scenes' }}"
                sequence:
                  - service: scene.turn_on
                    target:
                      entity_id: !input period2_scene

          - wait_for_trigger:
              - platform: state
                entity_id: !input motion_sensors
                to: 'off'
                for: !input period2_off_delay

          - service: light.turn_off
            target: !input off_lights

      # ---------- PERIOD 3 ----------
      - conditions:
          - condition: template
       >
              {% set now_time = now().strftime('%H:%M:%S') %}
              {% set start = period2_start %}
              {% set end = period2_end %}
              {% if start <= end %}
                {{ start <= now_time < end }}
              {% else %}
                {{ now_time >= start or now_time < end }}
              {% endif %}
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ control_mode == 'lights' }}"
                sequence:
                  - service: light.turn_on
                    target: !input period2_lights
                    da state
    entity_id: !input motion_sensors
    to: 'on'

action:
  - choose:
      # ---------- PERIOD 1 ----------
      - conditions:
          - condition: template
            value_template: >
              {% set now_time = now().strftime('%H:%M:%S') %}
              {% set start = period1_start %}
              {% set end = period1_end %}
              {% if start <= end %}
                {{ start <= now_time < end }}
              {% else %}
                {{ now_time >= start or now_time < end }}
              {% endif %}
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ control_mode == 'lights' }}"
                sequence:
                  - service: light.turn_on
                    target: !input period1_lights
                    data:
                      brightness_pct: !input period1_brightness
                      rgb_color: !input period1_color
              - conditions:
                  - condition: template
                    value_template: "{{ control_mode == 'scenes' }}"
                sequence:
                  - service: scene.turn_on
                    target:
                      entity_id: !input period1_scene

          - wait_for_trigger:
              - platform: state
                entity_id: !input motion_sensors
                to: 'off'
                for: !input period1_off_delay

          - service: light.turn_off
            target: !input off_lights

      # --slider
    period4_color:
      name: Period 4 RGB color
      description: RGB color for all selected lights in period 4.
      default: [255, 0, 0]
      selector:
        color_rgb:

    period4_scene:
      name: Period 4 scene
      description: Scene to activate in period 4 (used when Control mode = scenes).
      selector:
        entity:
          domain: scene

mode: restart
max_exceeded: silent

variables:
  control_mode: !input control_mode

  period1_start: !input period1_start
  period1_end: !input period1_end
  period2_start: !input period2_start
  period2_end: !input period2_end
  period3_start: !input period3_start
  period3_end: !input period3_end
  period4_start: !input period4_start
  period4_end: !input period4_end

trigger:
  - platform:
      name: Period 4 off delay
      description: How long after last motion to turn the lights off in period 4.
      default:
        hours: 0
        minutes: 5
        seconds: 0
      selector:
        duration:

    period4_lights:
      name: Period 4 lights
      description: Lights to control during period 4 (used when Control mode = lights).
      selector:
        target:
          entity:
            domain: light
    period4_brightness:
      name: Period 4 brightness
      description: Brightness in percent for all selected lights in period 4.
      default: 10
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: '%'
          mode:   name: Period 3 brightness
      description: Brightness in percent for all selected lights in period 3.
      default: 20
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: '%'
          mode: slider
    period3_color:
      name: Period 3 RGB color
      description: RGB color for all selected lights in period 3.
      default: [255, 0, 0]
      selector:
        color_rgb:

    period3_scene:
      name: Period 3 scene
      description: Scene to activate in period 3 (used when Control mode = scenes).
      selector:
        entity:
          domain: scene

    # -------- TIME PERIOD 4 --------
    period4_start:
      name: Period 4 start time
      selector:
        time:
    period4_end:
      name: Peri
        entity:
          domain: scene

    # -------- TIME PERIOD 3 --------
    period3_start:
      name: Period 3 start time
      selector:
        time:
    period3_end:
      name: Period 3 end time
      selector:
        time:
    period3_off_delay:
      name: Period 3 off delay
      description: How long after last motion to turn the lights off in period 3.
      default:
        hours: 0
        minutes: 10
        seconds: 0
      selector:
        duration:

    period3_lights:
      name: Period 3 lights
      description: Lights to control during period 3 (used when Control mode = lights).
      selector:
        target:
          entity:
            domain: light
    period3_brightness:
    

    period2_lights:
      name: Period 2 lights
      description: Lights to control during period 2 (used when Control mode = lights).
      selector:
        target:
          entity:
            domain: light
    period2_brightness:
      name: Period 2 brightness
      description: Brightness in percent for all selected lights in period 2.
      default: 40
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: '%'
          mode: slider
    period2_color:
      name: Period 2 RGB color
      description: RGB color for all selected lights in period 2.
      default: [255, 0, 0]
      selector:
        color_rgb:

    period2_scene:
      name: Period 2 scene
      description: Scene to activate in period 2 (u 1 RGB color
      description: RGB color for all selected lights in period 1.
      default: [255, 255, 255]
      selector:
        color_rgb:

    period1_scene:
      name: Period 1 scene
      description: Scene to activate in period 1 (used when Control mode = scenes).
      selector:
        entity:
          domain: scene

    # -------- TIME PERIOD 2 --------
    period2_start:
      name: Period 2 start time
      selector:
        time:
    period2_end:
      name: Period 2 end time
      selector:
        time:
    period2_off_delay:
      name: Period 2 off delay
      description: How long after last motion to turn the lights off in period 2.
      default:
        hours: 0
        minutes: 5
        seconds: 0
      selector:
        duration:
      description: How long after last motion to turn the lights off in period 1.
      default:
        hours: 0
        minutes: 5
        seconds: 0
      selector:
        duration:

    period1_lights:
      name: Period 1 lights
      description: >
        Lights to control during period 1 (any subset of your up-to-5 lights).
        Used when Control mode = lights.
      selector:
        target:
          entity:
            domain: light
    period1_brightness:
      name: Period 1 brightness
      description: Brightness in percent for all selected lights in period 1.
      default: 20
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: '%'
          mode: slider
    period1_color:
      name: Period
